import { Navbar } from '@/components/navbar';
import { Footer } from '@/components/footer';
import { SearchForm } from '@/components/search-form';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { MapPin, Sparkles, Users, TrendingUp } from 'lucide-react';

export default function Home() {
  const popularDestinations = [
    { name: 'Paris', image: '🗼', description: 'City of Light' },
    { name: 'Tokyo', image: '🗾', description: 'Modern Japan' },
    { name: 'Dubai', image: '🏜️', description: 'Desert Paradise' },
    { name: 'Bali', image: '🏝️', description: 'Tropical Haven' },
  ];

  const features = [
    {
      icon: Sparkles,
      title: 'AI-Powered Planning',
      description: 'Get personalized itineraries generated by advanced AI',
    },
    {
      icon: MapPin,
      title: 'Smart Hotel Search',
      description: 'Find hotels with map-based discovery and circle radius search',
    },
    {
      icon: Users,
      title: 'Collaborative Planning',
      description: 'Share trips with friends and plan together in real-time',
    },
    {
      icon: TrendingUp,
      title: 'Price Tracking',
      description: 'Get alerts when prices drop on your favorite hotels',
    },
  ];

  return (
    <>
      <Navbar />
      <main className="min-h-screen bg-gradient-to-b from-background via-background to-muted">
        {/* Hero Section */}
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <div className="text-center mb-12">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-foreground mb-4 text-balance">
              Your Next Adventure Starts Here
            </h1>
            <p className="text-lg text-foreground/70 mb-8 max-w-2xl mx-auto text-balance">
              Discover, plan, and book unforgettable trips with AI-powered recommendations, smart hotel search, and collaborative itinerary planning.
            </p>
          </div>

          {/* Search Form */}
          <SearchForm isHero={true} />
        </section>

        {/* Popular Destinations */}
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <h2 className="text-3xl font-bold text-foreground mb-12">Popular Destinations</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {popularDestinations.map((destination) => (
              <Link key={destination.name} href={`/hotels?destination=${destination.name}`}>
                <Card className="overflow-hidden hover:shadow-lg transition cursor-pointer h-full">
                  <div className="h-40 bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center text-6xl">
                    {destination.image}
                  </div>
                  <div className="p-6">
                    <h3 className="text-xl font-bold text-foreground mb-2">{destination.name}</h3>
                    <p className="text-foreground/60 text-sm">{destination.description}</p>
                  </div>
                </Card>
              </Link>
            ))}
          </div>
        </section>

        {/* Features Section */}
        <section className="bg-card/50 py-20">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <h2 className="text-3xl font-bold text-foreground mb-12 text-center">Why Choose Roameo?</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              {features.map((feature) => {
                const Icon = feature.icon;
                return (
                  <Card key={feature.title} className="p-8 text-center hover:shadow-md transition">
                    <div className="mb-4 flex justify-center">
                      <div className="bg-primary/10 p-4 rounded-lg">
                        <Icon className="w-8 h-8 text-primary" />
                      </div>
                    </div>
                    <h3 className="text-lg font-bold text-foreground mb-3">{feature.title}</h3>
                    <p className="text-foreground/60 text-sm">{feature.description}</p>
                  </Card>
                );
              })}
            </div>
          </div>
        </section>

        {/* Featured Deals */}
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <h2 className="text-3xl font-bold text-foreground mb-12">Limited Time Offers</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                title: 'Early Bird Special',
                description: 'Book 30 days in advance and save up to 40%',
                badge: 'Save 40%',
              },
              {
                title: 'Group Travel Discount',
                description: 'Book accommodations for 4+ people and get exclusive rates',
                badge: 'Up to 35% Off',
              },
              {
                title: 'Sustainability Rewards',
                description: 'Choose eco-friendly hotels and earn loyalty points',
                badge: '50 Points',
              },
            ].map((deal) => (
              <Card key={deal.title} className="p-8 border-primary/30 bg-gradient-to-br from-card to-card/50 hover:border-primary/60 transition">
                <div className="inline-block bg-primary text-primary-foreground px-3 py-1 rounded-full text-xs font-bold mb-4">
                  {deal.badge}
                </div>
                <h3 className="text-xl font-bold text-foreground mb-3">{deal.title}</h3>
                <p className="text-foreground/70 mb-6">{deal.description}</p>
                <Link href="/hotels">
                  <Button variant="outline" className="w-full">
                    Explore Deals
                  </Button>
                </Link>
              </Card>
            ))}
          </div>
        </section>

        {/* CTA Section */}
        <section className="bg-primary text-primary-foreground py-16">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <h2 className="text-3xl font-bold mb-4">Ready to Plan Your Dream Trip?</h2>
            <p className="text-lg opacity-90 mb-8">Join thousands of travelers using Roameo to discover and book amazing experiences.</p>
            <Link href="/hotels">
              <Button size="lg" variant="secondary">
                Start Exploring
              </Button>
            </Link>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
